[tool.poetry]
name = "alita_bot"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
python = "^3.13"

[tool.poetry.dependencies]
python-telegram-bot = "20.5"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
